homepage:
    path:     /
    defaults: { _controller: KulinariaMainBundle:Main:index }

cook_book:
    path: /cookBook/{page}
    defaults: { _controller: KulinariaMainBundle:CookBook:index, page: 1 }

find_recipt:
    path: /findRecipt
    defaults: { _controller: KulinariaMainBundle:Main:findRecipt }
