homepage:
    path:     /
    defaults: { _controller: KulinariaMainBundle:Main:index }

add_recipt:
    path:     /addRecipt
    defaults: { _controller: KulinariaMainBundle:Recipt:addRecipt }

show_recipts:
    path:     /showRecipts/{page}
    defaults: { _controller: KulinariaMainBundle:Recipt:showRecipts, page:1 }
