<?php

namespace Kulinaria\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReciptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReciptRepository extends EntityRepository
{
}
