Kulinaria\MainBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Kulinaria\MainBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nickname:
            type: string
            length: 255
        password:
            type: string
            length: 255
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        recipts:
            targetEntity: Recipt
            mappedBy: user
